import type { Property } from "./types"

export const featuredProperties: Property[] = [
  {
    id: "prop1",
    title: "Modern 2BHK Apartment in Downtown",
    description:
      "A beautiful modern apartment with all amenities in the heart of the city. Perfect for families or professionals.",
    price: 2500,
    location: "Downtown, New York",
    area: 1200,
    bhk: 2,
    bathrooms: 2,
    furnishing: "Semi-Furnished",
    floor: 5,
    totalFloors: 10,
    facing: "East",
    propertyType: "Apartment",
    listingType: "Rent",
    ownerType: "Owner",
    amenities: ["Gym", "Swimming Pool", "Security", "Parking", "Power Backup"],
    imageUrl: "/placeholder.svg?height=200&width=400",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    postedOn: "2 days ago",
    isVerified: true,
    contactName: "John Smith",
    contactPhone: "+1-234-567-8901",
    contactEmail: "john@example.com",
  },
  {
    id: "prop2",
    title: "Spacious 3BHK Villa with Garden",
    description:
      "Luxurious villa with a beautiful garden, modern amenities, and ample parking space in a gated community.",
    price: 4500,
    location: "Beverly Hills, Los Angeles",
    area: 2500,
    bhk: 3,
    bathrooms: 3,
    furnishing: "Fully Furnished",
    floor: 1,
    totalFloors: 2,
    facing: "South",
    propertyType: "Villa",
    listingType: "Rent",
    ownerType: "Owner",
    amenities: ["Garden", "Swimming Pool", "Security", "Parking", "Power Backup", "Home Theater"],
    imageUrl: "/placeholder.svg?height=200&width=400",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    postedOn: "1 week ago",
    isVerified: true,
    contactName: "Emily Johnson",
    contactPhone: "+1-345-678-9012",
    contactEmail: "emily@example.com",
  },
  {
    id: "prop3",
    title: "Cozy 1BHK Apartment Near Metro",
    description: "A cozy and affordable apartment with good connectivity, ideal for bachelors or small families.",
    price: 1200,
    location: "Midtown, Chicago",
    area: 750,
    bhk: 1,
    bathrooms: 1,
    furnishing: "Semi-Furnished",
    floor: 3,
    totalFloors: 8,
    facing: "West",
    propertyType: "Apartment",
    listingType: "Rent",
    ownerType: "Owner",
    amenities: ["Security", "Parking", "Power Backup", "Lift"],
    imageUrl: "/placeholder.svg?height=200&width=400",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    postedOn: "3 days ago",
    isVerified: true,
    contactName: "Michael Brown",
    contactPhone: "+1-456-789-0123",
    contactEmail: "michael@example.com",
  },
  {
    id: "prop4",
    title: "Luxury 4BHK Penthouse with Terrace",
    description:
      "Exclusive penthouse with a private terrace, panoramic city views, and premium amenities for a luxurious lifestyle.",
    price: 7500,
    location: "South Beach, Miami",
    area: 3200,
    bhk: 4,
    bathrooms: 4,
    furnishing: "Fully Furnished",
    floor: 20,
    totalFloors: 20,
    facing: "South-East",
    propertyType: "Penthouse",
    listingType: "Sale",
    ownerType: "Builder",
    amenities: ["Terrace", "Gym", "Swimming Pool", "Security", "Parking", "Power Backup", "Home Theater", "Spa"],
    imageUrl: "/placeholder.svg?height=200&width=400",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    postedOn: "2 weeks ago",
    isVerified: true,
    contactName: "Robert Wilson",
    contactPhone: "+1-567-890-1234",
    contactEmail: "robert@example.com",
  },
  {
    id: "prop5",
    title: "Commercial Office Space in Business District",
    description:
      "Prime commercial office space with modern infrastructure and amenities in the heart of the business district.",
    price: 5000,
    location: "Financial District, Houston",
    area: 1800,
    bhk: 0,
    bathrooms: 2,
    furnishing: "Semi-Furnished",
    floor: 10,
    totalFloors: 15,
    facing: "North",
    propertyType: "Commercial",
    listingType: "Rent",
    ownerType: "Owner",
    amenities: ["Conference Room", "Security", "Parking", "Power Backup", "Lift", "Cafeteria"],
    imageUrl: "/placeholder.svg?height=200&width=400",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    postedOn: "5 days ago",
    isVerified: true,
    contactName: "Jennifer Davis",
    contactPhone: "+1-678-901-2345",
    contactEmail: "jennifer@example.com",
  },
  {
    id: "prop6",
    title: "Student PG Accommodation Near University",
    description: "Affordable PG accommodation for students with all basic amenities and close to major universities.",
    price: 600,
    location: "University Area, Boston",
    area: 250,
    bhk: 1,
    bathrooms: 1,
    furnishing: "Fully Furnished",
    floor: 2,
    totalFloors: 4,
    facing: "East",
    propertyType: "PG/Hostel",
    listingType: "Rent",
    ownerType: "Owner",
    amenities: ["Wifi", "Meals", "Security", "Laundry", "Study Room"],
    imageUrl: "/placeholder.svg?height=200&width=400",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    postedOn: "1 day ago",
    isVerified: true,
    contactName: "Sarah Thompson",
    contactPhone: "+1-789-012-3456",
    contactEmail: "sarah@example.com",
  },
]
